POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"almuali699@gmail.com",
    "password":"password"
}

###

POST http://localhost:3000/resetPass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTg5ODg2LCJleHAiOjE2MDkxODk5NDZ9.mEcf5gyHvsoO1W14k-Eq32ZiSGonZuyE0kH3CaMzqOU
Content-Type: application/json

{
    "password": "password"
}

###

POST http://localhost:3000/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTg5OTM4LCJleHAiOjE2MDkxOTcxMzh9.3OzYnyeEe2IhFFWe6ZZp1pBeikFLcDFzQKpmQO-gW-w"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTg5OTM4LCJleHAiOjE2MDkxOTcxMzh9.3OzYnyeEe2IhFFWe6ZZp1pBeikFLcDFzQKpmQO-gW-w"
}

