POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"abc@yahoo.com",
    "password":"kamigamiX0!"
}

###

POST http://localhost:3000/resetPass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTg5ODg2LCJleHAiOjE2MDkxODk5NDZ9.mEcf5gyHvsoO1W14k-Eq32ZiSGonZuyE0kH3CaMzqOU
Content-Type: application/json

{
    "password": "password"
}

###

POST http://localhost:3000/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTkwMTMyLCJleHAiOjE2MDkxOTczMzJ9.a9MVEmbPLqYLhwNISVwxteOCtUZq79RmF-6Aaf2Ijqw"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbXVhbGk2OTlAZ21haWwuY29tIiwiaWF0IjoxNjA5MTkwNDI1LCJleHAiOjE2MDkxOTc2MjV9.80m5tKhk1wvpT1yjhyKUmsiZn4BNOmGeNKuiPBJ6P_g"
}

